git_dirs:
  - "Datakluis/Administratie privé"
  - "Datakluis/Belastingdienst"
  - "Datakluis/Blaeu Privacy Response Team B.V"
  - "Datakluis/Delia Natuurlijke Haarkleuring"
  - "Datakluis/Maandelijkse Checklist en Handleidingen"
  - "BAK/BAK Settings"
  - "Datakluis/Workspace/actief"
  - "Datakluis/Workspace/afgerond"
  - "Papers, presentations, webinars etc"
  - "Users/cursus en training"
  - "Users/dchin"
  - "Users/dharma/Niet weg, aantekeningen"
  - "Users/rvaneijk"
  - "Users/literatuur"

backup_folders:
  - dest: "AWS Outlook"
    source: "BAK/BAK Outlook"
    exclude: "AFGEROND.pst"
  - dest: "AWS Datakluis"
    source: "Datakluis/Administratie privé"
    exclude: ""
  - dest: "AWS Datakluis"
    source: "Datakluis/Belastingdienst"
    exclude: ""
  - dest: "AWS Datakluis"
    source: "Datakluis/Blaeu Privacy Response Team B.V"
    exclude: ""
  - dest: "AWS Datakluis"
    source: "Datakluis/Delia Natuurlijke Haarkleuring"
    exclude: ""
  - dest: "AWS Datakluis"
    source: "Datakluis/Maandelijkse Checklist en Handleidingen"
    exclude: ""
  - dest: "AWS Settings"
    source: "BAK/BAK Settings"
    exclude: ""
  - dest: "AWS Datakluis"
    source: "Datakluis/Workspace/actief"
    exclude: ".git .nuxt node_modules"