backup_type: INCR

backup_folders:
  - dest: "AWS Outlook"
    source: "BAK/BAK Outlook"
    archive_name: "Outlook"
    exclude: "AFGEROND.pst"
  - dest: "AWS Datakluis"
    source: "Datakluis/Administratie privé"
    archive_name: "Administratie privé"
    exclude: ""
  - dest: "AWS Datakluis"
    source: "Datakluis/Belastingdienst"
    archive_name: "Belastingdienst"
    exclude: ""
  - dest: "AWS Datakluis"
    source: "Datakluis/Blaeu Privacy Response Team B.V"
    archive_name: "Blaeu Privacy Response Team B.V"
    exclude: ""
  - dest: "AWS Datakluis"
    source: "Datakluis/Delia Natuurlijke Haarkleuring"
    archive_name: "Delia Natuurlijke Haarkleuring"
    exclude: ""
  - dest: "AWS Datakluis"
    source: "Datakluis/Maandelijkse Checklist en Handleidingen"
    archive_name: "Maandelijkse Checklist en Handleidingen"
    exclude: ""
  - dest: "AWS Settings"
    source: "BAK/BAK Settings"
    archive_name: "Settings"
    exclude: ""
  - dest: "AWS Datakluis"
    source: "Datakluis/Workspace/actief"
    archive_name: "Workspace actief"
    exclude: ".git .nuxt node_modules"