backup_type: FULL

allow_skip: true

backup_folders:
  - dest: "AWS Datakluis"
    source: "Datakluis"
    archive_name: "BAK Datakluis"
    exclude: ".git .nuxt node_modules"
  - dest: "AWS Onze cd's"
    source: "Onze cd's"
    archive_name: "BAK Onze cd's"
    exclude: ""
  - dest: "AWS Onze foto's"
    source: "Onze foto's"
    archive_name: "BAK Onze foto's"
    exclude: ""
  - dest: "AWS Outlook"
    source: "BAK/BAK Outlook"
    archive_name: "BAK Outlook"
    exclude: ""
  - dest: "AWS Papers, presentations, webinars etc"
    source: "Papers, presentations, webinars etc"
    archive_name: "BAK Papers, presentations, webinars etc"
    exclude: ""
  - dest: "AWS PhD_archive"
    source: "PhD_archive"
    archive_name: "INCR PhD_archive"
    exclude: ""
  - dest: "AWS Settings"
    source: "BAK/BAK Settings"
    archive_name: "BAK Settings"
    exclude: ""
  - dest: "AWS Tools"
    source: "Tools"
    archive_name: "BAK Tools"
    exclude: ""
  - dest: "AWS Users"
    source: "Users"
    archive_name: "BAK Users"
    exclude: "